### ISSUE TITLE
Github Helm Chart 

### ISSUE THREAD

**Issue by hupling** [it-at-m/.github#14]
- ein Chart zusammen für Frontend und Backend. also `helm install` und man hat alles
- helm create
-  lhm spezifische Sachen in die values.yml auslagern
- anders als das Dave-Projekt auch versuchen möglichst wenig Code zu kopieren. z. B. einmal eine Deployment erstellen und dann in den Sub-Charts darauf referenzieren

- [ ] helm create
- [ ] beispiel in https://github.com/it-at-m/helm-charts
- [ ] template erstellen

**Comment by hupling** [comment]
@banzuu https://github.com/it-at-m/helm-charts/tree/main/charts/refarch-gateway bitte auch das vom refarch-team anschauen

**Comment by hupling** [comment]
@simonhir @devtobi @DanielOber  also für mich macht das Chart refarch-gateway keinen Sinn. Es ist für mich sinnvoller, wenn es das Chart refarch gibt. Als externe Firma möchte ich keine 10 Helm-Charts brauchen für eine Software, sondern das Backend/Frontend in einem Helm Chart. Es wäre schön, wenn das SPS-Team eure MergeRequests zu Actions/Helm-Charts/Dockerfiles vor dem Mergen reviewen können. Weil sonst muss man wieder alles einzeln zusammenbasteln, um einen gleichen Stand zu haben, wie bei den Github-Actions jetzt. https://github.com/it-at-m/.github/issues/18

**Comment by simonhir** [comment]
Meiner Meinung nach stimmt das schon, weil du im Realfall, nur das Gateway übernimmst und der Rest individuell ist. Das heißt jeder Service hat ein eigenes Helm-Chart welches dann nur das Refarch-Gateway Helm Chart einbindet als Dependency.

Hab das bei DigiWF mal testweise gemacht, wobei hier jetzt noch eigene zusätzliche Services fehlen: https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/490

**Comment by hupling** [comment]
so sieht der neue stand aus:

- frontend  --> image ngix  ( nicht außen erreichbar)
- apigateway  -> leitet alles weiter (auf frontend/backend) (außen erreichbar)
- backend -> so wie bisher ( nicht außen erreichbar)

**Comment by hupling** [comment]
Ich habe erstmal eine docker-compose.yml 
```yml
name: sps-test
services: 
    frontend:
        image: ghcr.io/it-at-m/sps/sps-frontend:latest
        ports:
          - "8080:8080"
    backend:
        image: ghcr.io/it-at-m/sps/sps-backend:latest
        environment:
          SPRING_PROFILES_ACTIVE: openshift,dev,no-security
        ports:
          - "8082:8080"

        
    gateway1:
        image:     ghcr.io/it-at-m/refarch/refarch-gateway:1.0.0
        ports: 
         - "8083:8080"
        environment:
            SPRING_PROFILES_ACTIVE:  no-security
            SSO_ISSUER_URL: https://sso.muenchen.de/auth/realms/muenchen.de
              
              
              
            SPRING_CLOUD_GATEWAY_ROUTES_0_ID: backend
            SPRING_CLOUD_GATEWAY_ROUTES_0_URI: "http://host.docker.internal:8082/"
            SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/api/beispielprojekt-backend-service/**
            SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0: RewritePath=/api/beispielprojekt-backend-service/(?<urlsegments>.*), /$\{urlsegments}        
            SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_1: RemoveResponseHeader=WWW-Authenticate
             
             
            SPRING_CLOUD_GATEWAY_ROUTES_1_ID: frontend
            SPRING_CLOUD_GATEWAY_ROUTES_1_URI: "http://host.docker.internal:8080/"
            SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/**
            SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0: RewritePath=/(?<urlsegments>.*), /$\{urlsegments}        
            SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_1: RemoveResponseHeader=WWW-Authenticate
```
