### ISSUE TITLE
support mutlimodul projekte

### ISSUE THREAD

**Issue by hupling** [it-at-m/.github#89]
![grafik](https://github.com/user-attachments/assets/08ed576d-ec99-482d-8349-bef80ee953ee)

übergebe den ganzen pfad. z. b. `./backend` ` das war früher auch so

**Comment by hupling** [comment]
@simonhir ich hatte es wegen dir damals geändert. Erst später ist mir aufgefallen. dass so multiprojekte nicht mehr gehen. kann ich es wieder zurück ändern

**Comment by simonhir** [comment]
Why shouldn't this work for multi projects. We use it in the refarch which is a multiple project

**Comment by hupling** [comment]
@simonhir nein refarch ist ein monorepo. also mehrere projekte in einem git repo.

wenn jetzt jemand nur ein java projekte in einem repo hat geht es nicht. wegen dem pfad

**Comment by simonhir** [comment]
Think we did that because of the image name? Would you than add an additional property for that?

**Comment by hupling** [comment]
dann muss man das auch noch überarbeiten. Mit dem Image
```yml
        images: "${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}"
```

so könnte man es dann machen
```yml
      matrix:
        include: # hier müssen die Pfade angegeben werden
          - app-path: /refarch-backend
          - app-path: /refarch-frontend
          - app-path: ""
```
